#!/usr/bin/env python3
"""Run one optical simulation per telescope in an array manifest."""

import argparse
import csv
import re
import subprocess
import time
from pathlib import Path

from config_io import read_key_value_config, resolve_workspace_path


SUMMARY_KEYS = [
    "mirror_facets",
    "total_photons",
    "hit_mirror",
    "hit_output_plane",
    "hit_camera",
    "accepted_camera",
    "weighted_spot_rms_m",
    "output_csv",
]


def safe_name(text):
    cleaned = re.sub(r"[^A-Za-z0-9_.-]+", "_", text.strip())
    return cleaned.strip("_") or "telescope"


def read_array_rows(array_config):
    cfg = read_key_value_config(array_config)
    mode = cfg.get("mode", "csv").strip().lower()
    if mode != "csv":
        raise SystemExit(f"unsupported array mode: {mode}")
    csv_value = cfg.get("csv_path")
    if not csv_value:
        raise SystemExit("array config must define csv_path")

    csv_path = resolve_workspace_path(array_config, csv_value)
    rows = []
    with open(csv_path, newline="") as f:
        reader = csv.DictReader(f)
        for line_no, row in enumerate(reader, start=2):
            rows.append({
                "line_no": line_no,
                "telescope_id": int(row["telescope_id"]),
                "name": row["name"],
                "config_path": resolve_workspace_path(array_config, row["config_path"]),
                "position_x_m": float(row["position_x_m"]),
                "position_y_m": float(row["position_y_m"]),
                "position_z_m": float(row["position_z_m"]),
                "pointing_az_deg": float(row["pointing_az_deg"]),
                "pointing_el_deg": float(row["pointing_el_deg"]),
            })
    if not rows:
        raise SystemExit("array manifest has no telescope rows")
    return rows


def absolutize_component_paths(base_cfg, base_config):
    include_keys = {
        "telescope.config",
        "mirror.config",
        "source.config",
        "output.config",
        "camera.config",
        "sipm.config",
        "efficiency.config",
        "error.config",
    }
    out = dict(base_cfg)
    for key in include_keys:
        value = out.get(key)
        if value:
            path = Path(value)
            out[key] = str(path if path.is_absolute() else (base_config.parent / path).resolve())
    return out


def write_telescope_config(base_cfg, row, cfg_path, output_csv):
    merged = dict(base_cfg)
    merged["telescope.config"] = str(row["config_path"])
    merged["telescope.position_m"] = (
        f"{row['position_x_m']},{row['position_y_m']},{row['position_z_m']}"
    )
    merged["telescope.pointing_az_deg"] = str(row["pointing_az_deg"])
    merged["telescope.pointing_el_deg"] = str(row["pointing_el_deg"])
    merged["source.telescope_id"] = str(row["telescope_id"])
    # Synthetic sources ignore this key; PhotonCsv uses it to split one array
    # photon table into per-telescope streams.
    merged["source.filter_telescope_id"] = str(row["telescope_id"])
    merged["output.csv"] = str(output_csv)

    cfg_path.parent.mkdir(parents=True, exist_ok=True)
    with open(cfg_path, "w") as f:
        f.write("# Auto-generated by python/run_array_sim.py.\n")
        f.write("# Edit the array/base config, not this generated file.\n")
        for key in sorted(merged):
            f.write(f"{key}={merged[key]}\n")


def with_event_filter(base_cfg, event_id):
    merged = dict(base_cfg)
    if event_id is not None:
        merged["source.filter_event_id"] = str(event_id)
        merged["source.event_id"] = str(event_id)
    return merged


def parse_machine_summary(stdout):
    summary = {}
    for line in stdout.splitlines():
        if "=" not in line or line.startswith("["):
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip()
        if re.fullmatch(r"[A-Za-z0-9_]+", key):
            summary[key] = value
    return summary


def main():
    parser = argparse.ArgumentParser(
        description="Run LACT_sim optical simulation for each telescope in an array manifest."
    )
    parser.add_argument("--array-config", required=True)
    parser.add_argument("--base-config", default="configs/mirror_1229.cfg")
    parser.add_argument("--exe", default="build_check/run_optical_sim")
    parser.add_argument("--run-dir", default="run_logs/array_runs/latest")
    parser.add_argument(
        "--event-ids",
        default="",
        help="optional comma-separated event ids; each event is run in its own subdirectory",
    )
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    workspace = Path.cwd()
    array_config = Path(args.array_config).resolve()
    base_config = Path(args.base_config).resolve()
    exe = Path(args.exe).resolve()
    run_dir = Path(args.run_dir).resolve()
    run_dir.mkdir(parents=True, exist_ok=True)

    if not base_config.exists():
        raise SystemExit(f"missing base config: {base_config}")
    if not exe.exists():
        raise SystemExit(f"missing executable: {exe}")

    base_cfg = absolutize_component_paths(read_key_value_config(base_config), base_config)
    rows = read_array_rows(array_config)

    event_ids = []
    if args.event_ids.strip():
        event_ids = [int(x.strip()) for x in args.event_ids.split(",") if x.strip()]
    event_labels = event_ids if event_ids else [None]

    all_summary_rows = []
    print(f"Array telescopes = {len(rows)}")
    print(f"Run directory = {run_dir}")
    for event_id in event_labels:
        event_dir = run_dir if event_id is None else run_dir / f"event{event_id:03d}"
        event_dir.mkdir(parents=True, exist_ok=True)
        event_base_cfg = with_event_filter(base_cfg, event_id)
        summary_rows = []
        if event_id is not None:
            print(f"Event {event_id}")

        for row in rows:
            tag = f"tel{row['telescope_id']:03d}_{safe_name(row['name'])}"
            cfg_path = event_dir / f"{tag}.cfg"
            output_csv = event_dir / f"{tag}_hits.csv"
            log_path = event_dir / f"{tag}.log"
            write_telescope_config(event_base_cfg, row, cfg_path, output_csv)

            result = {
                "event_id": "" if event_id is None else event_id,
                "telescope_id": row["telescope_id"],
                "name": row["name"],
                "config": str(cfg_path),
                "log": str(log_path),
                "returncode": 0,
                "elapsed_s": "0.000",
            }
            print(
                f"  tel={row['telescope_id']} name={row['name']} "
                f"az/el=({row['pointing_az_deg']:.3f},{row['pointing_el_deg']:.3f})"
            )
            if args.dry_run:
                result["output_csv"] = str(output_csv)
                summary_rows.append(result)
                all_summary_rows.append(result)
                continue

            t0 = time.perf_counter()
            proc = subprocess.run(
                [str(exe), str(cfg_path)],
                cwd=str(workspace),
                text=True,
                capture_output=True,
                check=False,
            )
            elapsed = time.perf_counter() - t0
            with open(log_path, "w") as f:
                f.write("$ ")
                f.write(" ".join([str(exe), str(cfg_path)]))
                f.write("\n\n")
                f.write(proc.stdout)
                if proc.stderr:
                    f.write("\n[stderr]\n")
                    f.write(proc.stderr)

            result["returncode"] = proc.returncode
            result["elapsed_s"] = f"{elapsed:.3f}"
            result.update(parse_machine_summary(proc.stdout))
            summary_rows.append(result)
            all_summary_rows.append(result)
            if proc.returncode != 0:
                print(f"    failed returncode={proc.returncode} log={log_path}")
            else:
                rms = result.get("weighted_spot_rms_m", "n/a")
                hits = result.get("hit_output_plane", "n/a")
                print(f"    ok hits={hits} rms_m={rms} elapsed_s={elapsed:.3f}")

        summary_path = event_dir / "array_run_summary.csv"
        fieldnames = [
            "event_id",
            "telescope_id",
            "name",
            "config",
            "log",
            "returncode",
            "elapsed_s",
        ] + SUMMARY_KEYS
        with open(summary_path, "w", newline="") as f:
            writer = csv.DictWriter(f, fieldnames=fieldnames, extrasaction="ignore")
            writer.writeheader()
            writer.writerows(summary_rows)
        print(f"Saved summary = {summary_path}")

    summary_path = run_dir / "array_run_summary.csv"
    fieldnames = [
        "event_id",
        "telescope_id",
        "name",
        "config",
        "log",
        "returncode",
        "elapsed_s",
    ] + SUMMARY_KEYS
    with open(summary_path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(all_summary_rows)

    print(f"Saved combined summary = {summary_path}")
    if any(int(row["returncode"]) != 0 for row in all_summary_rows):
        raise SystemExit(1)


if __name__ == "__main__":
    main()
